package com.citrus.pottedplantskiosk.api.remote.dto

data class TransResponse(
    var source_package_name: String,
    var destination_package_name: String,
    var transaction_type: String,
    var card_number: String,
    var transaction_amount: String,
    var date_time: String,
    var expiry_date: String,
    var entry_mode: String,
    var retrieval_reference_number: String,
    var approval_code: String,
    var response_code: String,
    var terminal_id: String,
    var merchant_id: String,
    var host_label: String,
    var emv_data: String,
    var card_label: String,
    var card_type: String,
    var host_type: String,
    var command_identifier: String,
    var custom_data_2: String,
    var custom_data_3: String,
    var ecr_unique_trace_number: String,
    var invoice_number: String,
    var transaction_info: String,
    var batch_number: String,
    var coupons_vouchers: String,
    var additional_printing_flag: String,
    var external_device_invoice: String,
    var card_holder_name: String,
    var employee_id: String,
    var original_trans_type: String
)